var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(){function g(a){throw a;}
var k=void 0,l=!0,n=null,q=!1,s,t=this,aa=function(){},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},ca=function(a){return a!==k},u=function(a){return"array"==ba(a)},da=function(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length},w=function(a){return"string"==typeof a},fa=function(a){return"number"==typeof a},y=function(a){return"function"==ba(a)},ga=function(a){var b=typeof a;return"object"==b&&a!=n||"function"==b},ja=function(a){return a[ha]||
(a[ha]=++ia)},ha="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ia=0,ka=function(a,b,c){return a.call.apply(a.bind,arguments)},la=function(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},z=function(a,b,c){z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?
ka:la;return z.apply(n,arguments)},ma=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}},A=Date.now||function(){return+new Date},B=function(a,b){var c,d=b,e=a.split(".");c=c||t;!(e[0]in c)&&c.execScript&&c.execScript("var "+e[0]);for(var f;e.length&&(f=e.shift());)!e.length&&ca(d)?c[f]=d:c=c[f]?c[f]:c[f]={}},C=function(a,b){function c(){}c.prototype=b.prototype;a.f=b.prototype;a.prototype=
new c};var D=document,E=window;var na=function(a){Error.captureStackTrace?Error.captureStackTrace(this,na):this.stack=Error().stack||"";a&&(this.message=String(a))};C(na,Error);na.prototype.name="CustomError";var ua=function(a){var b;if(b)return a.replace(oa,"&amp;").replace(pa,"&lt;").replace(ra,"&gt;").replace(sa,"&quot;");if(!ta.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(oa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(pa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ra,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(sa,"&quot;"));return a},oa=/&/g,pa=/</g,ra=/>/g,sa=/\"/g,ta=/[&<>\"]/;var va=function(a,b){this.width=a;this.height=b};va.prototype.fa=function(){return new va(this.width,this.height)};va.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};va.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};va.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var wa=function(a,b,c){var d=l;a.addEventListener?a.addEventListener(b,c,d||q):a.attachEvent&&a.attachEvent("on"+b,c)},xa=function(a){var b=E;b.google_image_requests||(b.google_image_requests=[]);var c=b.document.createElement("img");c.src=a;b.google_image_requests.push(c)},ya=function(a){return!!a&&(0<a.indexOf("?google_debug")||0<a.indexOf("&google_debug"))};var za=function(){};za.prototype.ya=q;za.prototype.ma=function(){this.ya||(this.ya=l,this.b())};za.prototype.b=function(){this.Ge&&Aa.apply(n,this.Ge);if(this.Kd)for(;this.Kd.length;)this.Kd.shift()()};var F=function(a){a&&"function"==typeof a.ma&&a.ma()},Aa=function(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];da(d)?Aa.apply(n,d):F(d)}};var G=Array.prototype,Ba=G.indexOf?function(a,b,c){return G.indexOf.call(a,b,c)}:function(a,b,c){c=c==n?0:0>c?Math.max(0,a.length+c):c;if(w(a))return!w(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ca=G.forEach?function(a,b,c){G.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=w(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Da=G.some?function(a,b,c){return G.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=w(a)?a.split(""):a,
f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return l;return q},Ea=function(a,b){var c=Ba(a,b);if(0<=c){var d=a;G.splice.call(d,c,1)}},Fa=function(a){return G.concat.apply(G,arguments)},Ga=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ha=Ga,Ia=function(a,b,c){return 2>=arguments.length?G.slice.call(a,b):G.slice.call(a,b,c)};var Ja=[],Ka=q;var La=function(a,b){var c,d;for(d in a)b.call(c,a[d],d,a)},Ma=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Na=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Pa=function(){var a=Oa,b;for(b in a)return q;return l},Qa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Ra=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Qa.length;f++)c=Qa[f],Object.prototype.hasOwnProperty.call(d,
c)&&(a[c]=d[c])}};var Sa,Ta,Ua,Va,Wa,Xa,Ya=function(){return t.navigator?t.navigator.userAgent:n},Za=function(){return t.navigator};Va=Ua=Ta=Sa=q;var $a;if($a=Ya()){var ab=Za();Sa=0==$a.indexOf("Opera");Ta=!Sa&&-1!=$a.indexOf("MSIE");Ua=!Sa&&-1!=$a.indexOf("WebKit");Va=!Sa&&!Ua&&"Gecko"==ab.product}var bb=Sa,H=Ta,I=Va,J=Ua,cb,db=Za(),eb=cb=db&&db.platform||"";Wa=-1!=eb.indexOf("Mac");Xa=!!Za()&&-1!=(Za().appVersion||"").indexOf("X11");var fb=Wa,gb=Xa,hb=function(){var a=t.document;return a?a.documentMode:k},ib;
a:{var jb="",kb;if(bb&&t.opera)var lb=t.opera.version,jb="function"==typeof lb?lb():lb;else if(I?kb=/rv\:([^\);]+)(\)|;)/:H?kb=/MSIE\s+([^\);]+)(\)|;)/:J&&(kb=/WebKit\/(\S+)/),kb)var mb=kb.exec(Ya()),jb=mb?mb[1]:"";if(H){var nb=hb();if(nb>parseFloat(jb)){ib=String(nb);break a}}ib=jb}
var ob=ib,pb={},K=function(a){var b;if(!(b=pb[a])){b=pb;var c=a,d=a;a=ob;var e=0;a=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split(".");for(var d=String(d).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(a.length,d.length),h=0;0==e&&h<f;h++){var j=a[h]||"",m=d[h]||"",p=RegExp("(\\d*)(\\D*)","g"),r=RegExp("(\\d*)(\\D*)","g");do{var x=p.exec(j)||["","",""],v=r.exec(m)||["","",""];if(0==x[0].length&&0==v[0].length)break;var e=0==x[1].length?0:parseInt(x[1],10),qa=0==v[1].length?0:parseInt(v[1],
10),e=(e<qa?-1:e>qa?1:0)||((0==x[2].length)<(0==v[2].length)?-1:(0==x[2].length)>(0==v[2].length)?1:0)||(x[2]<v[2]?-1:x[2]>v[2]?1:0)}while(0==e)}a=e;b=b[c]=0<=a}return b},qb;var rb=t.document;if(rb&&H){var sb=hb();qb=sb||("CSS1Compat"==rb.compatMode?parseInt(ob,10):5)}else qb=k;var tb=qb;var ub=function(a){ub[" "](a);return a};ub[" "]=aa;var vb=function(a,b){try{return ub(a[b]),l}catch(c){}return q};var wb=!H||H&&9<=tb,xb=H&&!K("9");!J||K("528");I&&K("1.9b")||H&&K("8")||bb&&K("9.5")||J&&K("528");I&&!K("8")||H&&K("9");var yb=function(a,b){this.type=a;this.currentTarget=this.target=b};s=yb.prototype;s.b=function(){};s.ma=function(){};s.Na=q;s.defaultPrevented=q;s.Gb=l;s.preventDefault=function(){this.defaultPrevented=l;this.Gb=q};var zb=function(a,b){a&&this.Cb(a,b)};C(zb,yb);s=zb.prototype;s.target=n;s.relatedTarget=n;s.offsetX=0;s.offsetY=0;s.clientX=0;s.clientY=0;s.screenX=0;s.screenY=0;s.button=0;s.keyCode=0;s.charCode=0;s.ctrlKey=q;s.altKey=q;s.shiftKey=q;s.metaKey=q;s.uc=n;
s.Cb=function(a,b){var c=this.type=a.type;yb.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;d?I&&(vb(d,"nodeName")||(d=n)):"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=J||a.offsetX!==k?a.offsetX:a.layerX;this.offsetY=J||a.offsetY!==k?a.offsetY:a.layerY;this.clientX=a.clientX!==k?a.clientX:a.pageX;this.clientY=a.clientY!==k?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=
a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.uc=a;a.defaultPrevented&&this.preventDefault();delete this.Na};s.preventDefault=function(){zb.f.preventDefault.call(this);var a=this.uc;if(a.preventDefault)a.preventDefault();else if(a.returnValue=q,xb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};s.Oa=function(){return this.uc};
s.b=function(){};var Ab=function(){},Bb=0;s=Ab.prototype;s.key=0;s.ta=q;s.vc=q;s.Cb=function(a,b,c,d,e,f){y(a)?this.Ad=l:a&&a.handleEvent&&y(a.handleEvent)?this.Ad=q:g(Error("Invalid listener argument"));this.La=a;this.md=b;this.src=c;this.type=d;this.capture=!!e;this.yb=f;this.vc=q;this.key=++Bb;this.ta=q};s.handleEvent=function(a){return this.Ad?this.La.call(this.yb||this.src,a):this.La.handleEvent.call(this.La,a)};var Cb={},L={},Db={},Eb="on",Fb={},M=function(a,b,c,d,e){if(b){if(u(b)){for(var f=0;f<b.length;f++)M(a,b[f],c,d,e);return n}d=!!d;var h=L;b in h||(h[b]={d:0,D:0});h=h[b];d in h||(h[d]={d:0,D:0},h.d++);var h=h[d],j=ja(a),m;h.D++;if(h[j]){m=h[j];for(f=0;f<m.length;f++)if(h=m[f],h.La==c&&h.yb==e){if(h.ta)break;return m[f].key}}else m=h[j]=[],h.d++;var p=Gb,r=wb?function(a){return p.call(r.src,r.key,a)}:function(a){a=p.call(r.src,r.key,a);if(!a)return a},f=r;f.src=a;h=new Ab;h.Cb(c,f,a,b,d,e);c=h.key;
f.key=c;m.push(h);Cb[c]=h;Db[j]||(Db[j]=[]);Db[j].push(h);a.addEventListener?(a==t||!a.kd)&&a.addEventListener(b,f,d):a.attachEvent(b in Fb?Fb[b]:Fb[b]=Eb+b,f);return c}g(Error("Invalid event type"))},Hb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)Hb(a,b[f],c,d,e);else a=M(a,b,c,d,e),a=Cb[a],a.vc=l},Ib=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)Ib(a,b[f],c,d,e);else if(d=!!d,a=Jb(a,b,d))for(f=0;f<a.length;f++)if(a[f].La==c&&a[f].capture==d&&a[f].yb==e){N(a[f].key);break}},N=
function(a){if(!Cb[a])return q;var b=Cb[a];if(b.ta)return q;var c=b.src,d=b.type,e=b.md,f=b.capture;c.removeEventListener?(c==t||!c.kd)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in Fb?Fb[d]:Fb[d]=Eb+d,e);c=ja(c);Db[c]&&(e=Db[c],Ea(e,b),0==e.length&&delete Db[c]);b.ta=l;if(b=L[d][f][c])b.wd=l,Kb(d,f,c,b);delete Cb[a];return l},Kb=function(a,b,c,d){if(!d.Fb&&d.wd){for(var e=0,f=0;e<d.length;e++)if(d[e].ta){var h=d[e].md;h.src=n}else e!=f&&(d[f]=d[e]),f++;d.length=f;d.wd=q;0==f&&(delete L[a][b][c],
L[a][b].d--,0==L[a][b].d&&(delete L[a][b],L[a].d--),0==L[a].d&&delete L[a])}},Lb=function(a,b){var c,d=0,e=a==n,f=b==n,h=c==n;c=!!c;if(e)La(Db,function(a){for(var e=a.length-1;0<=e;e--){var j=a[e];if((f||b==j.type)&&(h||c==j.capture))N(j.key),d++}});else if(e=ja(a),Db[e])for(var e=Db[e],j=e.length-1;0<=j;j--){var m=e[j];if((f||b==m.type)&&(h||c==m.capture))N(m.key),d++}},Jb=function(a,b,c){var d=L;return b in d&&(d=d[b],c in d&&(d=d[c],a=ja(a),d[a]))?d[a]:n},Nb=function(a,b,c,d,e){var f=1;b=ja(b);
if(a[b]){a.D--;a=a[b];a.Fb?a.Fb++:a.Fb=1;try{for(var h=a.length,j=0;j<h;j++){var m=a[j];m&&!m.ta&&(f&=Mb(m,e)!==q)}}finally{a.Fb--,Kb(c,d,b,a)}}return Boolean(f)},Mb=function(a,b){a.vc&&N(a.key);return a.handleEvent(b)},Gb=function(a,b){if(!Cb[a])return l;var c=Cb[a],d=c.type,e=L;if(!(d in e))return l;var e=e[d],f,h;if(!wb){var j;if(!(j=b))a:{var m;j="window.event";j=j.split(".");for(m=m||t;f=j.shift();)if(m[f]!=n)m=m[f];else{j=n;break a}j=m}f=j;m=l in e;j=q in e;if(m){if(0>f.keyCode||f.returnValue!=
k)return l;a:{var p=f,r=q;if(0==p.keyCode)try{p.keyCode=-1;break a}catch(x){r=l}if(r||p.returnValue==k)p.returnValue=l}}p=new zb;p.Cb(f,this);f=l;try{if(m){for(var v=[],qa=p.currentTarget;qa;qa=qa.parentNode)v.push(qa);h=e[l];h.D=h.d;for(var ea=v.length-1;!p.Na&&0<=ea&&h.D;ea--)p.currentTarget=v[ea],f&=Nb(h,v[ea],d,l,p);if(j){h=e[q];h.D=h.d;for(ea=0;!p.Na&&ea<v.length&&h.D;ea++)p.currentTarget=v[ea],f&=Nb(h,v[ea],d,q,p)}}else f=Mb(c,p)}finally{v&&(v.length=0)}return f}d=new zb(b,this);return f=Mb(c,
d)};if(Ka)for(var Ob=0;Ob<Ja.length;Ob++)var Pb=z(Ja[Ob].Pe,Ja[Ob]),Gb=Pb(Gb);var Qb=function(){};C(Qb,za);s=Qb.prototype;s.kd=l;s.zb=n;s.gc=function(a){this.zb=a};s.addEventListener=function(a,b,c,d){M(this,a,b,c,d)};s.removeEventListener=function(a,b,c,d){Ib(this,a,b,c,d)};
s.dispatchEvent=function(a){var b=a.type||a,c=L;if(b in c){if(w(a))a=new yb(a,this);else if(a instanceof yb)a.target=a.target||this;else{var d=a;a=new yb(b,this);Ra(a,d)}var d=1,e,c=c[b],b=l in c,f;if(b){e=[];for(f=this;f;f=f.zb)e.push(f);f=c[l];f.D=f.d;for(var h=e.length-1;!a.Na&&0<=h&&f.D;h--)a.currentTarget=e[h],d&=Nb(f,e[h],a.type,l,a)&&a.Gb!=q}if(f=q in c)if(f=c[q],f.D=f.d,b)for(h=0;!a.Na&&h<e.length&&f.D;h++)a.currentTarget=e[h],d&=Nb(f,e[h],a.type,q,a)&&a.Gb!=q;else for(e=this;!a.Na&&e&&f.D;e=
e.zb)a.currentTarget=e,d&=Nb(f,e,a.type,q,a)&&a.Gb!=q;a=Boolean(d)}else a=l;return a};s.b=function(){Qb.f.b.call(this);Lb(this);this.zb=n};var Sb=function(a,b){this.Ma=a||1;this.Za=b||Rb;this.sc=z(this.ye,this);this.tc=A()};C(Sb,Qb);Sb.prototype.enabled=q;var Rb=t.window,Tb=0.8;s=Sb.prototype;s.Z=n;s.ye=function(){if(this.enabled){var a=A()-this.tc;0<a&&a<this.Ma*Tb?this.Z=this.Za.setTimeout(this.sc,this.Ma-a):(this.dispatchEvent("tick"),this.enabled&&(this.Z=this.Za.setTimeout(this.sc,this.Ma),this.tc=A()))}};s.start=function(){this.enabled=l;this.Z||(this.Z=this.Za.setTimeout(this.sc,this.Ma),this.tc=A())};
s.stop=function(){this.enabled=q;this.Z&&(this.Za.clearTimeout(this.Z),this.Z=n)};s.b=function(){Sb.f.b.call(this);this.stop();delete this.Za};var Ub=function(a,b,c){y(a)?c&&(a=z(a,c)):a&&"function"==typeof a.handleEvent?a=z(a.handleEvent,a):g(Error("Invalid listener argument"));return 2147483647<b?-1:Rb.setTimeout(a,b||0)};var Vb=function(a,b,c){this.Xa=a;this.Ma=b||0;this.sa=c;this.cb=z(this.rc,this)};C(Vb,za);s=Vb.prototype;s.g=0;s.b=function(){Vb.f.b.call(this);this.stop();delete this.Xa;delete this.sa};s.start=function(a){this.stop();this.g=Ub(this.cb,ca(a)?a:this.Ma)};s.stop=function(){this.bb()&&Rb.clearTimeout(this.g);this.g=0};s.bb=function(){return 0!=this.g};s.rc=function(){this.g=0;this.Xa&&this.Xa.call(this.sa)};var O=function(a,b){this.x=ca(a)?a:0;this.y=ca(b)?b:0};O.prototype.fa=function(){return new O(this.x,this.y)};var Wb,Xb=!H||H&&9<=tb;!I&&!H||H&&H&&9<=tb||I&&K("1.9.1");H&&K("9");var Yb=function(a,b){var c;c=a.className;c=w(c)&&c.match(/\S+/g)||[];for(var d=Ia(arguments,1),e=c.length+d.length,f=c,h=0;h<d.length;h++)0<=Ba(f,d[h])||f.push(d[h]);a.className=c.join(" ");return c.length==e};var P=function(a){return a?new Zb($b(a)):Wb||(Wb=new Zb)},ac={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},bc=function(a){a=a.document;a="CSS1Compat"==a.compatMode?a.documentElement:a.body;return new va(a.clientWidth,a.clientHeight)},cc=function(a,b){a.appendChild(b)},dc=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},
ec=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},$b=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},Zb=function(a){this.H=a||t.document||document};Zb.prototype.I=P;var fc=function(a){return a.H};s=Zb.prototype;s.z=function(a){return w(a)?this.H.getElementById(a):a};
s.wa=function(a,b,c){var d,e=this.H,f=arguments;d=f[0];var h=f[1];if(!Xb&&h&&(h.name||h.type)){d=["<",d];h.name&&d.push(' name="',ua(h.name),'"');if(h.type){d.push(' type="',ua(h.type),'"');var j={};Ra(j,h);delete j.type;h=j}d.push(">");d=d.join("")}d=e.createElement(d);if(h)if(w(h))d.className=h;else if(u(h))Yb.apply(n,[d].concat(h));else{var m=d;La(h,function(a,b){"style"==b?m.style.cssText=a:"class"==b?m.className=a:"for"==b?m.htmlFor=a:b in ac?m.setAttribute(ac[b],a):0==b.lastIndexOf("aria-",
0)||0==b.lastIndexOf("data-",0)?m.setAttribute(b,a):m[b]=a})}if(2<f.length)for(var p=e,r=d,e=f,h=2,f=function(a){a&&r.appendChild(w(a)?p.createTextNode(a):a)};h<e.length;h++)if(j=e[h],da(j)&&!(ga(j)&&0<j.nodeType)){var x=Ca,v;a:{if((v=j)&&"number"==typeof v.length){if(ga(v)){v="function"==typeof v.item||"string"==typeof v.item;break a}if(y(v)){v="function"==typeof v.item;break a}}v=q}x(v?Ga(j):j,f)}else f(j);return d};s.createElement=function(a){return this.H.createElement(a)};s.createTextNode=function(a){return this.H.createTextNode(a)};
s.c=function(){return this.H.parentWindow||this.H.defaultView};var gc=function(a){var b=a.H;a=!J&&"CSS1Compat"==b.compatMode?b.documentElement:b.body;b=b.parentWindow||b.defaultView;return a=new O(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)};Zb.prototype.appendChild=cc;Zb.prototype.contains=ec;var hc=function(a){this.sa=a;this.i=[]};C(hc,za);var ic=[],jc=function(a,b,c,d){var e,f;u(c)||(ic[0]=c,c=ic);for(var h=0;h<c.length;h++){var j=M(b,c[h],d||a,e||q,f||a.sa||a);a.i.push(j)}},kc=function(a,b,c,d,e,f){if(u(c))for(var h=0;h<c.length;h++)kc(a,b,c[h],d,e,f);else{a:{d=d||a;f=f||a.sa||a;e=!!e;if(b=Jb(b,c,e))for(c=0;c<b.length;c++)if(!b[c].ta&&b[c].La==d&&b[c].capture==e&&b[c].yb==f){b=b[c];break a}b=n}b&&(b=b.key,N(b),Ea(a.i,b))}},lc=function(a){Ca(a.i,N);a.i.length=0};
hc.prototype.b=function(){hc.f.b.call(this);lc(this)};hc.prototype.handleEvent=function(){g(Error("EventHandler.handleEvent not implemented"))};var mc=function(a){if(/^\s*$/.test(a))return q;var b=/\\["\\\/bfnrtu]/g,c=/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(c,"]").replace(d,""))},nc=function(a){a=String(a);if(mc(a))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))},qc=function(a){var b;b=new oc(b);var c=[];pc(b,a,c);return a=c.join("")},oc=function(a){this.Kb=
a},pc=function(a,b,c){switch(typeof b){case "string":rc(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==n){c.push("null");break}if(u(b)){var d=a;a=b;b=a.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=a[f],pc(d,d.Kb?d.Kb.call(a,String(f),e):e,c),e=",";c.push("]");break}c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),
rc(d,c),c.push(":"),pc(a,a.Kb?a.Kb.call(b,d,e):e,c),f=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}},sc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},tc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g,rc=function(a,b){b.push('"',a.replace(tc,function(a){if(a in sc)return sc[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return sc[a]=
e+b.toString(16)}),'"')};var uc="StopIteration"in t?t.StopIteration:Error("StopIteration"),vc=function(){};vc.prototype.next=function(){g(uc)};vc.prototype.He=function(){return this};var wc=function(a){if("function"==typeof a.$)return a.$();if(w(a))return a.split("");if(da(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ma(a)};var xc=function(a,b){this.O={};this.i=[];var c=arguments.length;if(1<c){c%2&&g(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){d=a;d instanceof xc?(c=d.Ka(),d=d.$()):(c=Na(d),d=Ma(d));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};s=xc.prototype;s.d=0;s.Eb=0;s.$=function(){yc(this);for(var a=[],b=0;b<this.i.length;b++){var c=this.i[b];a.push(this.O[c])}return a};s.Ka=function(){yc(this);return this.i.concat()};
s.ab=function(a){return zc(this.O,a)};s.remove=function(a){return zc(this.O,a)?(delete this.O[a],this.d--,this.Eb++,this.i.length>2*this.d&&yc(this),l):q};var yc=function(a){if(a.d!=a.i.length){for(var b=0,c=0;b<a.i.length;){var d=a.i[b];zc(a.O,d)&&(a.i[c++]=d);b++}a.i.length=c}if(a.d!=a.i.length){for(var e={},c=b=0;b<a.i.length;)d=a.i[b],zc(e,d)||(a.i[c++]=d,e[d]=1),b++;a.i.length=c}};xc.prototype.get=function(a,b){return zc(this.O,a)?this.O[a]:b};
xc.prototype.set=function(a,b){zc(this.O,a)||(this.d++,this.i.push(a),this.Eb++);this.O[a]=b};xc.prototype.fa=function(){return new xc(this)};xc.prototype.He=function(a){yc(this);var b=0,c=this.i,d=this.O,e=this.Eb,f=this,h=new vc;h.next=function(){for(;;){e!=f.Eb&&g(Error("The map has changed since the iterator was created"));b>=c.length&&g(uc);var h=c[b++];return a?h:d[h]}};return h};var zc=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Ac=function(){this.mb={}};C(Ac,za);Ac.prototype.G=function(a){a&&a()};Ac.prototype.v=function(){return l};var Bc=function(a,b){var c,d="expandable_ad";a.mb[d]={T:b,cd:!!c}},Cc=function(a,b){if(b&&w(a))try{return nc(a)}catch(c){return n}else if(!b&&!w(a))return qc(a);return a};Ac.prototype.b=function(){Ac.f.b.call(this);F(this.oe);delete this.oe;delete this.mb;delete this.Kc};var Dc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),Fc=function(a){if(Ec){Ec=q;var b=t.location;if(b){var c=b.href;if(c){var d=3;if((c=(c=Fc(c)[d]||n)&&decodeURIComponent(c))&&c!=b.hostname)Ec=l,g(Error())}}}return a.match(Dc)},Ec=J,Gc=function(a){var b=Fc(a),c;a=b[1];var d=b[2],e=b[3],b=b[4],f,h,j="";a&&(j+=a+":");e&&(j+="//",d&&(j+=d+"@"),j+=e,b&&(j+=":"+b));c&&(j+=c);f&&(j+="?"+f);h&&(j+="#"+h);return c=j};var Hc=function(a,b){var c;if(a instanceof Hc)this.B=ca(b)?b:a.B,Ic(this,a.Y),c=a.oa,Q(this),this.oa=c,c=a.K,Q(this),this.K=c,Jc(this,a.ha),c=a.L,Q(this),this.L=c,Kc(this,a.A.fa()),c=a.na,Q(this),this.na=c;else if(a&&(c=Fc(String(a)))){this.B=!!b;Ic(this,c[1]||"",l);var d=c[2]||"";Q(this);this.oa=d?decodeURIComponent(d):"";d=c[3]||"";Q(this);this.K=d?decodeURIComponent(d):"";Jc(this,c[4]);d=c[5]||"";Q(this);this.L=d?decodeURIComponent(d):"";Kc(this,c[6]||"",l);c=c[7]||"";Q(this);this.na=c?decodeURIComponent(c):
""}else this.B=!!b,this.A=new Lc(n,0,this.B)},Mc=q;s=Hc.prototype;s.Y="";s.oa="";s.K="";s.ha=n;s.L="";s.na="";s.Je=q;s.B=q;s.toString=function(){var a=[],b=this.Y;b&&a.push(Nc(b,Oc),":");if(b=this.K){a.push("//");var c=this.oa;c&&a.push(Nc(c,Oc),"@");a.push(encodeURIComponent(String(b)));b=this.ha;b!=n&&a.push(":",String(b))}if(b=this.L)this.K&&"/"!=b.charAt(0)&&a.push("/"),a.push(Nc(b,"/"==b.charAt(0)?Pc:Qc));(b=this.A.toString())&&a.push("?",b);(b=this.na)&&a.push("#",Nc(b,Rc));return a.join("")};
s.fa=function(){return new Hc(this)};var Ic=function(a,b,c){Q(a);a.Y=c?b?decodeURIComponent(b):"":b;a.Y&&(a.Y=a.Y.replace(/:$/,""))},Jc=function(a,b){Q(a);b?(b=Number(b),(isNaN(b)||0>b)&&g(Error("Bad port number "+b)),a.ha=b):a.ha=n},Kc=function(a,b,c){Q(a);b instanceof Lc?(a.A=b,a.A.wc(a.B)):(c||(b=Nc(b,Sc)),a.A=new Lc(b,0,a.B))},Q=function(a){a.Je&&g(Error("Tried to modify a read-only Uri"))};Hc.prototype.wc=function(a){this.B=a;this.A&&this.A.wc(a);return this};
var Tc=function(a){var b;return a instanceof Hc?a.fa():new Hc(a,b)},Nc=function(a,b){return w(a)?encodeURI(a).replace(b,Uc):n},Uc=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Oc=/[#\/\?@]/g,Qc=/[\#\?:]/g,Pc=/[\#\?]/g,Sc=/[\#\?@]/g,Rc=/#/g,Lc=function(a,b,c){this.C=a||n;this.B=!!c},Wc=function(a){if(!a.h&&(a.h=new xc,a.d=0,a.C))for(var b=a.C.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=n,f=n;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];
e=decodeURIComponent(e.replace(/\+/g," "));e=Vc(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}};s=Lc.prototype;s.h=n;s.d=n;s.add=function(a,b){Wc(this);this.C=n;a=Vc(this,a);var c=this.h.get(a);c||this.h.set(a,c=[]);c.push(b);this.d++;return this};s.remove=function(a){Wc(this);a=Vc(this,a);return this.h.ab(a)?(this.C=n,this.d-=this.h.get(a).length,this.h.remove(a)):q};s.ab=function(a){Wc(this);a=Vc(this,a);return this.h.ab(a)};
s.Ka=function(){Wc(this);for(var a=this.h.$(),b=this.h.Ka(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};s.$=function(a){Wc(this);var b=[];if(a)this.ab(a)&&(b=Fa(b,this.h.get(Vc(this,a))));else{a=this.h.$();for(var c=0;c<a.length;c++)b=Fa(b,a[c])}return b};s.set=function(a,b){Wc(this);this.C=n;a=Vc(this,a);this.ab(a)&&(this.d-=this.h.get(a).length);this.h.set(a,[b]);this.d++;return this};
s.get=function(a,b){var c=a?this.$(a):[];return Mc?0<c.length?c[0]:b:0<c.length?String(c[0]):b};s.toString=function(){if(this.C)return this.C;if(!this.h)return"";for(var a=[],b=this.h.Ka(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.$(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}return this.C=a.join("&")};s.fa=function(){var a=new Lc;a.C=this.C;this.h&&(a.h=this.h.fa(),a.d=this.d);return a};
var Vc=function(a,b){var c=String(b);a.B&&(c=c.toLowerCase());return c};
Lc.prototype.wc=function(a){var b=a&&!this.B;if(b){Wc(this);this.C=n;var c=this.h,b=function(a,b){var c=b.toLowerCase();if(b!=c){this.remove(b);var d=a;this.remove(c);0<d.length&&(this.C=n,this.h.set(Vc(this,c),Ha(d)),this.d+=d.length)}};if("function"==typeof c.forEach)c.forEach(b,this);else if(da(c)||w(c))Ca(c,b,this);else{var d;var e=c;if("function"==typeof e.Ka)d=e.Ka();else if("function"!=typeof e.$)if(da(e)||w(e)){d=[];for(var e=e.length,f=0;f<e;f++)d.push(f)}else d=Na(e);else d=k;c=wc(c);e=
c.length;for(f=0;f<e;f++)b.call(this,c[f],d&&d[f])}}this.B=a};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var R=function(a,b){this.Db=[];this.vd=a;this.jd=b||n};s=R.prototype;s.J=q;s.eb=q;s.fb=0;s.qc=q;s.ne=q;s.Ab=0;s.cancel=function(a){if(this.J)this.$a instanceof R&&this.$a.cancel();else{if(this.n){var b=this.n;delete this.n;a?b.cancel(a):(a=b,a.Ab--,0>=a.Ab&&a.cancel())}this.vd?this.vd.call(this.jd,this):this.qc=l;this.J||this.qd(new Xc)}};s.nd=function(a,b){Yc(this,a,b);this.fb--;0==this.fb&&this.J&&Zc(this)};
var Yc=function(a,b,c){a.J=l;a.$a=c;a.eb=!b;Zc(a)},ad=function(a){a.J&&(a.qc||g(new $c),a.qc=q)};R.prototype.T=function(a){ad(this);Yc(this,l,a)};R.prototype.qd=function(a){ad(this);Yc(this,q,a)};var bd=function(a,b,c,d){a.Db.push([b,c,d]);a.J&&Zc(a)},cd=function(a,b){var c=z(b.Ie,b);bd(a,c,n,k)};R.prototype.Ie=function(a){var b=new R;bd(this,b.T,b.qd,b);a&&(b.n=this,this.Ab++);return b};
var dd=function(a){return Da(a.Db,function(a){return y(a[1])})},Zc=function(a){a.oc&&(a.J&&dd(a))&&(t.clearTimeout(a.oc),delete a.oc);a.n&&(a.n.Ab--,delete a.n);for(var b=a.$a,c=q,d=q;a.Db.length&&0==a.fb;){var e=a.Db.shift(),f=e[0],h=e[1],e=e[2];if(f=a.eb?h:f)try{var j=f.call(e||a.jd,b);ca(j)&&(a.eb=a.eb&&(j==b||j instanceof Error),a.$a=b=j);b instanceof R&&(d=l,a.fb++)}catch(m){b=m,a.eb=l,dd(a)||(c=l)}}a.$a=b;d&&a.fb&&(bd(b,z(a.nd,a,l),z(a.nd,a,q)),b.ne=l);c&&(a.oc=t.setTimeout(function(){g(b)},
0))},$c=function(){na.call(this)};C($c,na);$c.prototype.message="Deferred has already fired";$c.prototype.name="AlreadyCalledError";var Xc=function(){na.call(this)};C(Xc,na);Xc.prototype.message="Deferred was cancelled";Xc.prototype.name="CancelledError";var ed=["pu","lru","pru","lpu","ppu"],S={},gd=function(){var a,b=10;a=a||fd;for(var c=a.length,d="";0<b--;)d+=a.charAt(Math.floor(Math.random()*c));return d},fd="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var hd=function(a){this.r=a||P()};C(hd,za);hd.prototype.ua=0;hd.prototype.c=function(){return this.r.c()};var id=function(a,b){this.r=b||P();this.a=a;this.Ua=[];this.Yd=z(this.ke,this)};C(id,hd);s=id.prototype;s.ua=2;s.dc=q;s.Z=0;s.G=function(){0==jd(this.a)?(this.X=this.a.Aa,this.X.XPC_toOuter=z(this.Uc,this)):this.Tc()};
s.Tc=function(){var a=l;try{this.X||(this.X=this.c().frameElement),this.X&&this.X.XPC_toOuter&&(this.Zb=this.X.XPC_toOuter,this.X.XPC_toOuter.XPC_toInner=z(this.Uc,this),a=q,this.send("tp","SETUP_ACK"),this.a.W())}catch(b){}a&&(this.$c||(this.$c=z(this.Tc,this)),this.c().setTimeout(this.$c,100))};s.hc=function(a){0==jd(this.a)&&!this.a.v()&&"SETUP_ACK"==a?(this.Zb=this.X.XPC_toOuter.XPC_toInner,this.a.W()):g(Error("Got unexpected transport message."))};
s.Uc=function(a,b){!this.dc&&0==this.Ua.length?this.a.U(a,b):(this.Ua.push({$d:a,$b:b}),1==this.Ua.length&&(this.Z=this.c().setTimeout(this.Yd,1)))};s.ke=function(){for(;this.Ua.length;){var a=this.Ua.shift();this.a.U(a.$d,a.$b)}};s.send=function(a,b){this.dc=l;this.Zb(a,b);this.dc=q};s.b=function(){id.f.b.call(this);this.X=this.Zb=n};var T=function(a,b){this.r=b||P();this.a=a;this.Ra=this.a.l.ppu;this.fe=this.a.l.lpu;this.xb=[]},kd,ld;C(T,hd);s=T.prototype;s.Ud=5;s.ua=4;s.jc=0;s.Ha=q;s.la=q;s.Oc=n;var md=function(a){return"googlexpc_"+a.a.name+"_msg"},nd=function(a){return"googlexpc_"+a.a.name+"_ack"},pd=function(a){try{if(!a.ya&&od(a.a))return a.a.V.frames||{}}catch(b){}return{}};
T.prototype.G=function(){if(!this.ya&&od(this.a)){if(!this.la){var a=md(this);this.Ea=qd(this,a);this.Vb=this.c().frames[a];a=nd(this);this.Da=qd(this,a);this.Ub=this.c().frames[a];this.la=l}if(!rd(this,md(this))||!rd(this,nd(this))){if(1==jd(this.a))this.Oc||0<this.Ud--||(this.a.name=gd(),sd(this),this.la=q,this.Oc=qd(this,"googlexpc_reconnect_"+this.a.name));else if(0==jd(this.a))for(var a=pd(this),b=a.length,c=0;c<b;c++){var d;try{a[c]&&a[c].name&&(d=a[c].name)}catch(e){}if(d){var f=d.split("_");
if(3==f.length&&"googlexpc"==f[0]&&"reconnect"==f[1]){this.a.name=f[2];sd(this);this.la=q;break}}}this.c().setTimeout(z(this.G,this),100)}else this.Dc=new td(this,pd(this)[md(this)],z(this.Wd,this)),this.Cc=new td(this,pd(this)[nd(this)],z(this.Vd,this)),this.Gc()}};
var qd=function(a,b){var c;c="iframe";c=document.createElement(c);var d=c.style;d.position="absolute";d.top="-10px";d.left="10px";d.width="1px";d.height="1px";c.id=c.name=b;c.src=a.Ra+"#INITIAL";a.c().document.body.appendChild(c);return c},sd=function(a){a.Ea&&(a.Ea.parentNode.removeChild(a.Ea),a.Ea=n,a.Vb=n);a.Da&&(a.Da.parentNode.removeChild(a.Da),a.Da=n,a.Ub=n)},rd=function(a,b){try{var c=pd(a)[b];if(!c||0!=c.location.href.indexOf(a.fe))return q}catch(d){return q}return l};
T.prototype.Gc=function(){var a=pd(this);!a[nd(this)]||!a[md(this)]?(this.pd||(this.pd=z(this.Gc,this)),this.c().setTimeout(this.pd,100)):(this.ld=new ud(this.Ra,this.Vb),this.wb=new ud(this.Ra,this.Ub),this.c().setTimeout(z(function(){this.ld.send("SETUP");this.Ha=l},this),100))};var vd=function(a){if(a.Zc&&a.ce&&(a.a.W(),a.Ya)){for(var b=0,c;b<a.Ya.length;b++)c=a.Ya[b],a.a.U(c.ee,c.$b);delete a.Ya}};
T.prototype.Wd=function(a){if("SETUP"==a)this.wb&&(this.wb.send("SETUP_ACK"),this.Zc=l,vd(this));else if(this.a.v()||this.Zc){var b=a.indexOf("|"),c=a.substring(0,b);a=a.substring(b+1);b=c.indexOf(",");if(-1==b){var d=c;this.wb.send("ACK:"+d);wd(this,a)}else d=c.substring(0,b),this.wb.send("ACK:"+d),c=c.substring(b+1).split("/"),b=parseInt(c[0],10),c=parseInt(c[1],10),1==b&&(this.lc=[]),this.lc.push(a),b==c&&(wd(this,this.lc.join("")),delete this.lc)}};
T.prototype.Vd=function(a){"SETUP_ACK"==a?(this.Ha=q,this.ce=l,vd(this)):this.a.v()&&this.Ha&&(a=parseInt(a.split(":")[1],10),a==this.jc&&(this.Ha=q,xd(this)))};var xd=function(a){if(!a.Ha&&a.xb.length){var b=a.xb.shift();++a.jc;a.ld.send(a.jc+b);a.Ha=l}},wd=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c),c=b.substring(c+1);a.a.v()?a.a.U(d,c):(a.Ya||(a.Ya=[])).push({ee:d,$b:c})};T.prototype.Jb=3800;
T.prototype.send=function(a,b){var c=a+":"+b;if(!H||b.length<=this.Jb)this.xb.push("|"+c);else for(var d=b.length,e=Math.ceil(d/this.Jb),f=0,h=1;f<d;)this.xb.push(","+h+"/"+e+"|"+c.substr(f,this.Jb)),h++,f+=this.Jb;xd(this)};T.prototype.b=function(){T.f.b.call(this);var a=yd;Ea(a,this.Dc);Ea(a,this.Cc);this.Dc=this.Cc=n;dc(this.Ea);dc(this.Da);this.Vb=this.Ub=this.Ea=this.Da=n};
var yd=[],Ad=function(){var a=yd,b,c=q;try{for(var d=0;b=a[d];d++){var e;if(!(e=c)){var f=b,h=f.hd.location.href;if(h!=f.gd){f.gd=h;var j=h.split("#")[1];j&&(j=j.substr(1),f.je(decodeURIComponent(j)));e=l}else e=q}c=e}}catch(m){if(b.j.a.close(),!a.length)return}a=A();c&&(kd=a);c=1E3>a-kd?10:100;ld=window.setTimeout(zd,c)},zd=z(Ad,T),Bd=function(){kd=A();ld&&window.clearTimeout(ld);ld=window.setTimeout(zd,10)},ud=function(a,b){this.Ra=a;this.Hd=b;this.xc=0};
ud.prototype.send=function(a){this.xc=++this.xc%2;a=this.Ra+"#"+this.xc+encodeURIComponent(a);try{J?this.Hd.location.href=a:this.Hd.location.replace(a)}catch(b){}Bd()};var td=function(a,b,c){this.j=a;this.hd=b;this.je=c;this.gd=this.hd.location.href.split("#")[0]+"#INITIAL";yd.push(this);Bd()};var Ed=function(a,b){this.r=b||P();this.a=a;this.ae=this.a.l.pru;this.Vc=this.a.l.ifrid;J&&(Cd||(Cd=window.setTimeout(function(){Dd()},1E3)))};C(Ed,hd);if(J)var Fd=[],Cd=0,Dd=function(a){var b=A();for(a=a||3E3;Fd.length&&b-Fd[0].timestamp>=a;){var c=Fd.shift().ge;dc(c)}Cd=window.setTimeout(Gd,1E3)},Gd=function(){Dd()};var Hd={};Ed.prototype.ua=3;Ed.prototype.G=function(){this.c().xpcRelay||(this.c().xpcRelay=Id);this.send("tp","SETUP")};
var Id=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c),e=b.substr(c+1);if(!H||-1==(c=d.indexOf("|")))var f=d;else{var f=d.substr(0,c),d=d.substr(c+1),c=d.indexOf("+"),h=d.substr(0,c),c=parseInt(d.substr(c+1),10),j=Hd[h];j||(j=Hd[h]={Cd:[],Dd:0,Bd:0});-1!=d.indexOf("++")&&(j.Bd=c+1);j.Cd[c]=e;j.Dd++;if(j.Dd!=j.Bd)return;e=j.Cd.join("");delete Hd[h]}S[a].U(f,decodeURIComponent(e))};Ed.prototype.hc=function(a){"SETUP"==a?(this.send("tp","SETUP_ACK"),this.a.W()):"SETUP_ACK"==a&&this.a.W()};
Ed.prototype.send=function(a,b){var c=encodeURIComponent(b),d=c.length,e=1800;if(H&&d>e){var f;f=2147483648;f=Math.floor(Math.random()*f).toString(36)+Math.abs(Math.floor(Math.random()*f)^A()).toString(36);for(var h=0,j=0;h<d;j++){var m=c.substr(h,e),h=h+e,p=f+(h>=d?"++":"+")+j;Jd(this,a,m,p)}}else Jd(this,a,c)};
var Jd=function(a,b,c,d){if(H){var e=a.c().document.createElement("div");e.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';e=e.childNodes[0];e.xpcOnload=Kd}else e=a.c().document.createElement("iframe"),J?Fd.push({timestamp:A(),ge:e}):M(e,"load",Kd);var f=e.style;f.visibility="hidden";f.width=e.style.height="0px";f.position="absolute";f=a.ae;f+="#"+a.a.name;a.Vc&&(f+=","+a.Vc);f+="|"+b;d&&(f+="|"+d);f+=":"+c;e.src=f;a.c().document.body.appendChild(e)},Kd=function(){dc(this)};
Ed.prototype.b=function(){Ed.f.b.call(this);J&&Dd(0)};var U=function(a,b,c,d,e){this.r=c||P();this.a=a;this.Ca=e||2;this.Lb=b||"*";this.Tb=new hc(this);this.Qa=new Sb(100,this.c());this.Wb=!!d;this.ea=new R;this.da=new R;this.ga=new R;this.Sd=gd();this.nb=n;this.Wb?1==jd(this.a)?cd(this.ga,this.ea):cd(this.ga,this.da):(cd(this.ga,this.ea),2==this.Ca&&cd(this.ga,this.da));bd(this.ga,this.Hc,n,this);this.ga.T(l);jc(this.Tb,this.Qa,"tick",this.Fc)};C(U,hd);U.prototype.w=n;U.prototype.la=q;U.prototype.ua=1;
var Ld={},Nd=function(a){var b=a.Oa().data;if(!w(b))return q;var c=b.indexOf("|"),d=b.indexOf(":");if(-1==c||-1==d)return q;var e=b.substring(0,c),c=b.substring(c+1,d),b=b.substring(d+1);if(d=S[e])return d.U(c,b,a.Oa().origin),l;a=Md(b)[0];for(var f in S)if(d=S[f],1==jd(d)&&!d.v()&&"tp"==c&&("SETUP"==a||"SETUP_NTPV2"==a))return d.name=e,delete S[f],S[e]=d,d.U(c,b),l;return q};
U.prototype.hc=function(a){var b=Md(a);a=b[0];b=b[1];switch(a){case "SETUP_ACK":Od(this,1);this.ea.J||this.ea.T(l);break;case "SETUP_ACK_NTPV2":2==this.Ca&&(Od(this,2),this.ea.J||this.ea.T(l));break;case "SETUP":Od(this,1);Pd(this,1);break;case "SETUP_NTPV2":2==this.Ca&&(a=this.w,Od(this,2),Pd(this,2),(1==a||this.nb!=n)&&this.nb!=b&&Qd(this),this.nb=b)}};
var Qd=function(a){if(2==a.Ca&&(a.w==n||2==a.w)){var b="SETUP_NTPV2",b=b+",",b=b+a.Sd;a.send("tp",b)}(a.w==n||1==a.w)&&a.send("tp","SETUP")},Pd=function(a,b){if(2==a.Ca&&(a.w==n||2==a.w)&&2==b)a.send("tp","SETUP_ACK_NTPV2");else if((a.w==n||1==a.w)&&1==b)a.send("tp","SETUP_ACK");else return;a.da.J||a.da.T(l)},Od=function(a,b){b>a.w&&(a.w=b);1==a.w&&(!a.da.J&&!a.Wb&&a.da.T(l),a.nb=n)};s=U.prototype;
s.G=function(){var a=this.c(),b=ja(a),c=Ld[b];fa(c)||(c=0);0==c&&M(a.postMessage?a:a.document,"message",Nd,q,U);Ld[b]=c+1;this.la=l;this.Fc()};s.Fc=function(){var a=0==jd(this.a);this.Wb&&a||this.a.v()||this.ya?this.Qa.stop():(this.Qa.start(),Qd(this))};s.send=function(a,b){var c=this.a.V;c&&(this.send=function(a,b){var f=this,h=this.a.name,j=function(){f.ob=0;try{var j=c.postMessage?c:c.document;j.postMessage&&j.postMessage(h+"|"+a+":"+b,f.Lb)}catch(p){}};this.ob=Ub(j,0)},this.send(a,b))};
s.Hc=function(){var a=1==this.Ca||1==this.w?200:k;this.a.W(a)};s.b=function(){if(this.la){var a=this.c(),b=ja(a),c=Ld[b];Ld[b]=c-1;1==c&&Ib(a.postMessage?a:a.document,"message",Nd,q,U)}this.ob&&(Rb.clearTimeout(this.ob),this.ob=0);F(this.Tb);delete this.Tb;F(this.Qa);delete this.Qa;this.ea.cancel();delete this.ea;this.da.cancel();delete this.da;this.ga.cancel();delete this.ga;delete this.send;U.f.b.call(this)};var Md=function(a){a=a.split(",");a[1]=a[1]||n;return a};var Rd=function(a,b){this.r=b||P();this.a=a;this.Lc=a.at||"";this.Pc=a.rat||"";var c=this.c();if(!c.nix_setup_complete){var d="Class GCXPC____NIXVBS_wrapper\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport.GCXPC____NIXJS_handle_message(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport.GCXPC____NIXJS_create_channel(channel)\nEnd Sub\nPublic Sub GCXPC____NIXVBS_container()\n End Sub\nEnd Class\n Function GCXPC____NIXVBS_get_wrapper(transport, auth)\nDim wrap\nSet wrap = New GCXPC____NIXVBS_wrapper\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet GCXPC____NIXVBS_get_wrapper = wrap\nEnd Function";
try{c.execScript(d,"vbscript"),c.nix_setup_complete=l}catch(e){}}this.GCXPC____NIXJS_handle_message=this.Ba;this.GCXPC____NIXJS_create_channel=this.de};C(Rd,hd);s=Rd.prototype;s.ua=6;s.Ia=q;s.ra=n;s.G=function(){0==jd(this.a)?this.ad():this.Wc()};s.ad=function(){if(!this.Ia){var a=this.a.Aa;try{var b=this.c(),c=b.GCXPC____NIXVBS_get_wrapper;a.contentWindow.opener=c(this,this.Lc);this.Ia=l}catch(d){}this.Ia||this.c().setTimeout(z(this.ad,this),100)}};
s.Wc=function(){if(!this.Ia){try{var a=this.c().opener;if(a&&"GCXPC____NIXVBS_container"in a){this.ra=a;var b=this.ra.GetAuthToken();if(b!=this.Pc)return;var c=this.c(),d=c.GCXPC____NIXVBS_get_wrapper;this.ra.CreateChannel(d(this,this.Lc));this.Ia=l;this.a.W()}}catch(e){return}this.Ia||this.c().setTimeout(z(this.Wc,this),100)}};s.de=function(a){this.ra=a;a=this.ra.GetAuthToken();a==this.Pc&&this.a.W()};s.Ba=function(a,b){var c=function(){this.a.U(a,b)};this.c().setTimeout(z(c,this),1)};
s.send=function(a,b){this.ra.SendMessage(a,b)};s.b=function(){Rd.f.b.call(this);this.ra=n};var Td=function(a,b){this.mb={};for(var c=0,d;d=ed[c];c++)d in a&&!/^https?:\/\//.test(a[d])&&g(Error("URI "+a[d]+" is invalid for field "+d));this.l=a;this.name=this.l.cn||gd();this.r=b||P();this.lb=[];this.Yb=new hc(this);a.lpu=a.lpu||Gc(this.r.c().location.href)+"/robots.txt";a.ppu=a.ppu||Gc(a.pu||"")+"/robots.txt";S[this.name]=this;M(window,"unload",Sd)};C(Td,Ac);var Ud=/^%*tp$/,Vd=/^%+tp$/;s=Td.prototype;s.ia=n;s.pa=n;s.j=n;s.o=1;s.v=function(){return 2==this.o};s.V=n;s.Aa=n;
var od=function(a){try{return!!a.V&&!Boolean(a.V.closed)}catch(b){return q}};s=Td.prototype;s.G=function(a){this.kc=a||aa;this.pa?bd(this.pa,this.Fd,n,k):this.Fd()};
s.Fd=function(){this.pa=n;this.l.ifrid&&(this.Aa=this.r.z(this.l.ifrid));if(this.Aa){var a=this.Aa.contentWindow;a||(a=window.frames[this.l.ifrid]);this.V=a}this.V||(window==window.top&&g(Error("CrossPageChannel: Can't connect, peer window-object not set.")),this.V=window.parent);if(!this.j){if(!this.l.tp){var a=this.l,b;if(y(document.postMessage)||y(window.postMessage)||H&&window.postMessage)b=1;else if(I)b=2;else if(H&&this.l.pru)b=3;else{var c;if(c=H){c=q;try{b=window.opener,window.opener={},c=
vb(window,"opener"),window.opener=b}catch(d){}}b=c?6:4}a.tp=b}switch(this.l.tp){case 1:a=this.l.nativeProtocolVersion||2;this.j=new U(this,this.l.ph,this.r,!!this.l.osh,a);break;case 6:this.j=new Rd(this,this.r);break;case 2:this.j=new id(this,this.r);break;case 3:this.j=new Ed(this,this.r);break;case 4:this.j=new T(this,this.r)}this.j||g(Error("CrossPageChannel: No suitable transport found!"))}for(this.j.G();0<this.lb.length;)this.lb.shift()()};
s.close=function(){this.pa&&(this.pa.cancel(),this.pa=n);this.lb.length=0;lc(this.Yb);this.o=3;F(this.j);this.kc=this.j=n;F(this.ia);this.ia=n};s.W=function(a){this.v()||this.ia&&this.ia.bb()||(this.o=2,F(this.ia),a?(this.ia=new Vb(this.kc,a),this.ia.start()):(this.ia=n,this.kc()))};s.Hc=Td.prototype.W;s.send=function(a,b){this.v()&&(od(this)?(ga(b)&&(b=qc(b)),this.j.send(Wd(a),b)):this.close())};
s.U=function(a,b,c){if(this.pa)this.lb.push(z(this.U,this,a,b,c));else{var d=this.l.ph;if((c=/^[\s\xa0]*$/.test(c==n?"":String(c))||/^[\s\xa0]*$/.test(d==n?"":String(d))||c==this.l.ph)&&!this.ya)!a||"tp"==a?this.j.hc(b):this.v()&&(a=a.replace(/%[0-9a-f]{2}/gi,decodeURIComponent),a=Vd.test(a)?a.substring(1):a,c=b,(d=this.mb[a])?a=d:this.Kc?(a=ma(this.Kc,a),c=ga(c),a={T:a,cd:c}):a=n,a&&(b=Cc(b,a.cd),b!=n&&a.T(b)))}};
var Wd=function(a){Ud.test(a)&&(a="%"+a);return a.replace(/[%:|]/g,encodeURIComponent)},jd=function(a){var b=a.l.role;return b?b:window.parent==a.V?1:0};Td.prototype.b=function(){this.close();this.Aa=this.V=n;delete S[this.name];F(this.Yb);delete this.Yb;Td.f.b.call(this)};var Sd=function(){for(var a in S)F(S[a])};var Yd=function(a,b,c){w(b)?Xd(a,c,b):La(b,ma(Xd,a))},Xd=function(a,b,c){a.style[String(c).replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()})]=b},V=function(a,b){var c;a:{c=b;var d=$b(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,n))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}return c||(a.currentStyle?a.currentStyle[b]:n)||a.style&&a.style[b]},$d=function(a,b,c){var d,e=I&&(fb||gb)&&K("1.9");b instanceof O?(d=b.x,b=b.y):(d=b,b=c);a.style.left=
Zd(d,e);a.style.top=Zd(b,e)},ae=function(a){var b=a.getBoundingClientRect();H&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b},be=function(a){if(H&&!(H&&8<=tb))return a.offsetParent;var b=$b(a),c=V(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=V(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||
"fixed"==c||"absolute"==c||"relative"==c))return a;return n},de=function(a){var b=new O;if(1==a.nodeType){if(a.getBoundingClientRect){var c=ae(a);b.x=c.left;b.y=c.top}else{var c=gc(P(a)),d;var e=a,f,h=$b(e),j=V(e,"position"),m=I&&h.getBoxObjectFor&&!e.getBoundingClientRect&&"absolute"==j&&(f=h.getBoxObjectFor(e))&&(0>f.screenX||0>f.screenY);d=new O(0,0);var p;f=h?$b(h):document;if(p=H)if(p=!(H&&9<=tb))p=P(f),p="CSS1Compat"==p.H.compatMode,p=!p;p=p?f.body:f.documentElement;if(e!=p)if(e.getBoundingClientRect)f=
ae(e),e=gc(P(h)),d.x=f.left+e.x,d.y=f.top+e.y;else if(h.getBoxObjectFor&&!m)f=h.getBoxObjectFor(e),e=h.getBoxObjectFor(p),d.x=f.screenX-e.screenX,d.y=f.screenY-e.screenY;else{m=e;do{d.x+=m.offsetLeft;d.y+=m.offsetTop;m!=e&&(d.x+=m.clientLeft||0,d.y+=m.clientTop||0);if(J&&"fixed"==V(m,"position")){d.x+=h.body.scrollLeft;d.y+=h.body.scrollTop;break}m=m.offsetParent}while(m&&m!=e);if(bb||J&&"absolute"==j)d.y-=h.body.offsetTop;for(m=e;(m=be(m))&&m!=h.body&&m!=p;)if(d.x-=m.scrollLeft,!bb||"TR"!=m.tagName)d.y-=
m.scrollTop}b.x=d.x-c.x;b.y=d.y-c.y}if(I&&!K(12)){var r;H?r="-ms-transform":J?r="-webkit-transform":bb?r="-o-transform":I&&(r="-moz-transform");var x;r&&(x=V(a,r));x||(x=V(a,"transform"));x?(a=x.match(ce),a=!a?new O(0,0):new O(parseFloat(a[1]),parseFloat(a[2]))):a=new O(0,0);b=new O(b.x+a.x,b.y+a.y)}}else r=y(a.Oa),x=a,a.targetTouches?x=a.targetTouches[0]:r&&a.Oa().targetTouches&&(x=a.Oa().targetTouches[0]),b.x=x.clientX,b.y=x.clientY;return b},ee=function(a,b,c){b instanceof va?(c=b.height,b=b.width):
c==k&&g(Error("missing height argument"));a.style.width=Zd(b,l);a.style.height=Zd(c,l)},Zd=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a},ge=function(a){if("none"!=V(a,"display"))return fe(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=fe(a);b.display=c;b.position=e;b.visibility=d;return a},fe=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=J&&!b&&!c;return(!ca(b)||d)&&a.getBoundingClientRect?(a=
ae(a),new va(a.right-a.left,a.bottom-a.top)):new va(b,c)},he=function(a,b){var c=a.style;"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*b+")")},W=function(a,b){a.style.display=b?"":"none"},ce=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;var ie=function(a,b,c){this.Xa=a;this.sa=c;this.P=b||window;this.cb=z(this.rc,this)};C(ie,za);s=ie.prototype;s.g=n;s.pc=q;s.start=function(){this.stop();this.pc=q;var a=je(this),b=ke(this);if(a&&!b&&this.P.mozRequestAnimationFrame)this.g=M(this.P,"MozBeforePaint",this.cb),this.P.mozRequestAnimationFrame(n),this.pc=l;else{if(a&&b)a=a.call(this.P,this.cb);else{var c=this.cb,d;d=d||0;a=function(){return c.apply(this,Array.prototype.slice.call(arguments,0,d))};a=this.P.setTimeout(a,20)}this.g=a}};
s.stop=function(){if(this.bb()){var a=je(this),b=ke(this);a&&!b&&this.P.mozRequestAnimationFrame?N(this.g):a&&b?b.call(this.P,this.g):this.P.clearTimeout(this.g)}this.g=n};s.bb=function(){return this.g!=n};s.rc=function(){this.pc&&this.g&&N(this.g);this.g=n;this.Xa.call(this.sa,A())};s.b=function(){this.stop();ie.f.b.call(this)};
var je=function(a){a=a.P;return a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.oRequestAnimationFrame||a.msRequestAnimationFrame||n},ke=function(a){a=a.P;return a.cancelRequestAnimationFrame||a.webkitCancelRequestAnimationFrame||a.mozCancelRequestAnimationFrame||a.oCancelRequestAnimationFrame||a.msCancelRequestAnimationFrame||n};var Oa={},le=n,me=n,ne=function(a){a=ja(a);delete Oa[a];Pa()&&me&&me.stop()},pe=function(){me||(me=le?new ie(function(a){oe(a)},le):new Vb(function(){oe(A())},20));var a=me;a.bb()||a.start()},oe=function(a){La(Oa,function(b){qe(b,a)});Pa()||pe()};var re=function(){this.o=0;this.rd=this.startTime=n};C(re,Qb);re.prototype.mc=function(){this.aa("begin")};re.prototype.Bb=function(){this.aa("end")};re.prototype.aa=function(a){this.dispatchEvent(a)};var X=function(a,b,c,d){re.call(this);(!u(a)||!u(b))&&g(Error("Start and end parameters must be arrays"));a.length!=b.length&&g(Error("Start and end points must be the same length"));this.gb=a;this.Be=b;this.duration=c;this.Ed=d;this.coords=[];this.Ae=q};C(X,re);X.prototype.F=0;
X.prototype.play=function(a){if(a||0==this.o)this.F=0,this.coords=this.gb;else if(1==this.o)return q;ne(this);this.startTime=a=A();-1==this.o&&(this.startTime-=this.duration*this.F);this.rd=this.startTime+this.duration;this.F||this.mc();this.aa("play");-1==this.o&&this.aa("resume");this.o=1;var b=ja(this);b in Oa||(Oa[b]=this);pe();qe(this,a);return l};X.prototype.stop=function(a){ne(this);this.o=0;a&&(this.F=1);se(this,this.F);this.aa("stop");this.Bb()};
X.prototype.b=function(){0==this.o||this.stop(q);this.aa("destroy");X.f.b.call(this)};var qe=function(a,b){a.F=(b-a.startTime)/(a.rd-a.startTime);1<=a.F&&(a.F=1);se(a,a.F);1==a.F?(a.o=0,ne(a),a.aa("finish"),a.Bb()):1==a.o&&a.nc()},se=function(a,b){y(a.Ed)&&(b=a.Ed(b));a.coords=Array(a.gb.length);for(var c=0;c<a.gb.length;c++)a.coords[c]=(a.Be[c]-a.gb[c])*b+a.gb[c]};X.prototype.nc=function(){this.aa("animate")};X.prototype.aa=function(a){this.dispatchEvent(new te(a,this))};
var te=function(a,b){yb.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.duration=b.duration;this.F=b.F;this.state=b.o};C(te,yb);var ue=function(a,b,c,d,e){X.call(this,b,c,d,e);this.element=a};C(ue,X);s=ue.prototype;s.Hb=aa;s.Jd=function(){ca(this.va)||(this.va="rtl"==V(this.element,"direction"));return this.va};s.nc=function(){this.Hb();ue.f.nc.call(this)};s.Bb=function(){this.Hb();ue.f.Bb.call(this)};s.mc=function(){this.Hb();ue.f.mc.call(this)};var ve=function(a,b,c,d,e){(2!=b.length||2!=c.length)&&g(Error("Start and end points must be 2D"));ue.apply(this,arguments)};C(ve,ue);
ve.prototype.Hb=function(){var a=this.Ae&&this.Jd()?"right":"left";this.element.style[a]=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var we=function(a){return 1-Math.pow(1-a,3)};var xe=function(a){this.k=a;a=H?"focusin":"focus";var b=H?"focusout":"blur";this.le=M(this.k,a,this,!H);this.me=M(this.k,b,this,!H)};C(xe,Qb);xe.prototype.handleEvent=function(a){var b=a.Oa(),b=new zb(b);b.type="focusin"==a.type||"focus"==a.type?"focusin":"focusout";this.dispatchEvent(b)};xe.prototype.b=function(){xe.f.b.call(this);N(this.le);N(this.me);delete this.k};var ye=function(){},ze=ye;ze.Ld=function(){return ze.Md?ze.Md:ze.Md=new ze};ye.prototype.xe=0;ye.Ld();var Y=function(a){this.kb=a||P();this.va=Ae};C(Y,Qb);Y.prototype.we=ye.Ld();var Ae=n;s=Y.prototype;s.g=n;s.ba=q;s.k=n;s.va=n;s.n=n;s.tb=n;s.sb=n;s.Zd=q;s.Rb=function(){return this.g||(this.g=":"+(this.we.xe++).toString(36))};s.z=function(){return this.k};var Be=function(a){return a.Ja||(a.Ja=new hc(a))};s=Y.prototype;s.gc=function(a){this.n&&this.n!=a&&g(Error("Method not supported"));Y.f.gc.call(this,a)};s.I=function(){return this.kb};s.wa=function(){this.k=this.kb.createElement("div")};
s.hb=function(){this.ba=l;Ce(this,function(a){!a.ba&&a.z()&&a.hb()})};s.za=function(){Ce(this,function(a){a.ba&&a.za()});this.Ja&&lc(this.Ja);this.ba=q};s.b=function(){Y.f.b.call(this);this.ba&&this.za();this.Ja&&(this.Ja.ma(),delete this.Ja);Ce(this,function(a){a.ma()});!this.Zd&&this.k&&dc(this.k);this.n=this.k=this.sb=this.tb=n};s.Jd=function(){this.va==n&&(this.va="rtl"==V(this.ba?this.k:this.kb.H.body,"direction"));return this.va};
var De=function(a,b){var c;if(a.sb&&b){c=a.sb;var d;c=(c=b in c?c[b]:d)||n}else c=n;return c},Ce=function(a,b){var c;a.tb&&Ca(a.tb,b,c)};
Y.prototype.removeChild=function(a,b){if(a){var c=w(a)?a:a.Rb();a=De(this,c);if(c&&a){var d=this.sb;c in d&&delete d[c];Ea(this.tb,a);b&&(a.za(),a.k&&dc(a.k));c=a;d=n;c==d&&g(Error("Unable to set parent component"));d&&(c.n&&c.g&&De(c.n,c.g)&&c.n!=d)&&g(Error("Unable to set parent component"));c.n=d;Y.f.gc.call(c,d)}}a||g(Error("Child is not in parent component"));return a};var Ee=function(a,b){Y.call(this,b);this.ie=!!a};C(Ee,Y);s=Ee.prototype;s.fc=n;s.rb=q;s.u=n;s.p=n;s.M=n;
s.wa=function(){Ee.f.wa.call(this);var a=this.z();Yb(a,"goog-modalpopup");a.tabIndex=0;W(a,q);if(this.ie&&!this.p){var b,a=this.I();this.p=b=a.wa("iframe",{frameborder:0,style:"border:0;vertical-align:bottom;"+(b||""),src:'javascript:""'});this.p.className="goog-modalpopup-bg";W(this.p,q);he(this.p,0)}this.u||(this.u=this.I().wa("div","goog-modalpopup-bg"),W(this.u,q));this.M||(this.M=this.I().createElement("span"),W(this.M,q),this.M.tabIndex=0,this.M.style.position="absolute")};
s.hb=function(){if(this.p){var a=this.z();a.parentNode&&a.parentNode.insertBefore(this.p,a)}a=this.z();a.parentNode&&a.parentNode.insertBefore(this.u,a);Ee.f.hb.call(this);a=this.z();a.parentNode&&a.parentNode.insertBefore(this.M,a.nextSibling);this.fc=new xe(fc(this.I()));jc(Be(this),this.fc,"focusin",this.he)};s.za=function(){this.rb&&Fe(this,q);F(this.fc);Ee.f.za.call(this);dc(this.p);dc(this.u);dc(this.M)};
var Fe=function(a,b){if(b!=a.rb)if(a.Ga&&a.Ga.stop(),a.Ta&&a.Ta.stop(),a.Fa&&a.Fa.stop(),a.Sa&&a.Sa.stop(),b){var c=a;if(c.dispatchEvent("beforeshow")){c.ic();var d=c,e=fc(d.I()),f=(e?e.parentWindow||e.defaultView:window)||window;if("fixed"==V(d.z(),"position"))var h=e=0;else h=gc(d.I()),e=h.x,h=h.y;var j=ge(d.z()),f=bc(f||window),e=Math.max(e+f.width/2-j.width/2,0),h=Math.max(h+f.height/2-j.height/2,0);$d(d.z(),e,h);$d(d.M,e,h);jc(Be(c),c.I().c(),"resize",c.ic);Ge(c,l);c.focus();c.rb=l;c.Ga&&c.Ta?
(Hb(c.Ga,"end",c.ed,q,c),c.Ta.play(),c.Ga.play()):c.ed()}}else c=a,c.dispatchEvent("beforehide")&&(kc(Be(c),c.I().c(),"resize",c.ic),c.rb=q,c.Fa&&c.Sa?(Hb(c.Fa,"end",c.dd,q,c),c.Sa.play(),c.Fa.play()):c.dd())},Ge=function(a,b){a.p&&W(a.p,b);a.u&&W(a.u,b);W(a.z(),b);W(a.M,b)};s=Ee.prototype;s.ed=function(){this.dispatchEvent("show")};s.dd=function(){Ge(this,q);this.dispatchEvent("hide")};s.focus=function(){this.Id()};
s.ic=function(){this.p&&W(this.p,q);this.u&&W(this.u,q);var a=fc(this.I()),b=(a?a.parentWindow||a.defaultView:window)||window,c=bc(b||window),b=Math.max(c.width,Math.max(a.body.scrollWidth,a.documentElement.scrollWidth)),a=Math.max(c.height,Math.max(a.body.scrollHeight,a.documentElement.scrollHeight));this.p&&(W(this.p,l),ee(this.p,b,a));this.u&&(W(this.u,l),ee(this.u,b,a))};s.he=function(a){a.target==this.M&&Ub(this.Id,0,this)};s.Id=function(){try{H&&fc(this.I()).body.focus(),this.z().focus()}catch(a){}};
s.b=function(){F(this.Ga);this.Ga=n;F(this.Fa);this.Fa=n;F(this.Ta);this.Ta=n;F(this.Sa);this.Sa=n;Ee.f.b.call(this)};var He=function(){this.Ib=[]},Z=function(a,b,c,d){a.Ib.push(new Ie(b,c,d))},Je=function(a,b){Z(a,b,"zIndex",999999)},Ke=function(a){for(var b=a.Ib.length-1;0<=b;b--){var c=a.Ib[b];c.Gd.style[c.Ce]=c.De}a.Ib.length=0},Ie=function(a,b,c){this.Gd=a;this.Ce=b;this.De=a.style[b];this.Gd.style[b]=c};var Le=function(a,b,c,d,e,f){this.m=a;this.R=b;this.ca=c;this.ka=d;this.be=e;this.qb=f;this.e=new He;this.Nd=300;this.xa=this.S=n;this.Wa=42};Le.prototype.zc=function(){this.qb()};
Le.prototype.Qd=function(){var a=de(this.m),b=ge(this.m),c=a.x-Math.floor(this.ca/2)+Math.floor(b.width/2),a=a.y-Math.floor(this.ka/2)+Math.floor(b.height/2),b=this.S.k,d=Math.floor(this.Wa/2);Z(this.e,b,"width",this.Wa+"px");Z(this.e,b,"height",this.Wa+"px");Z(this.e,b,"left",c+this.ca-d+"px");Z(this.e,b,"top",a-d+"px");Z(this.e,b,"background","transparent");Z(this.e,b,"border",0);var e=E.location.protocol,d="pagead2.googlesyndication.com",f=this.R.document.createElement("img");f.src=[e,"//",d,"/pagead/images/close_circle.png"].join("");
f.style.outline="none";f.style.zIndex=1E6;f.style.width=this.Wa+"px";f.style.height=this.Wa+"px";M(f,"mousedown",this.zc,q,this);b.appendChild(f);Z(this.e,this.m,"width",this.ca+"px");Z(this.e,this.m,"height",this.ka+"px");Z(this.e,this.m,"left",c+"px");Z(this.e,this.m,"top",a+"px");this.be()};var Me={NORMAL:0,LIGHTBOX:1,EXPANSION_MODES:2},Ne=function(a){a=a||D.location.protocol+"//"+D.location.host;return a+"/robots.txt"};var Oe=function(a,b,c,d,e,f){this.q=q;this.Xc=a;this.R=e;this.bd=f;this.Ac=b;this.t=+c;this.s=+d;this.e=new He;this.Pa=n;this.Pb=this.t;this.Ob=this.s;this.Qb=this.jb=n};s=Oe.prototype;s.ib=function(){return this.q};s.Nb=function(){return this.t};s.Mb=function(){return this.s};s.Rb=function(){return this.Xc};
s.collapse=function(){var a=Pe(this);if(a){if(this.Pa){a=this.Pa;1==a.xa.o&&(Lb(a.xa,"end"),a.xa.stop());a.S.za();var b=a.S.k;b&&a.R.document.body.removeChild(b);Ke(a.e);this.Pa=n}Ke(this.e);this.ja=this.q=q}};var Qe=function(a,b,c,d){Z(a.e,b,"width",c+"px");Z(a.e,b,"height",d+"px");Je(a.e,b)},Re=function(a){var b=[],c=Pe(a);if(!c)return b;b.push(c);a.R&&a.bd&&b.push(a.R.document.getElementById(a.bd));return b};
Oe.prototype.expand=function(a,b,c){var d=Re(this);if(!(0>=d.length)){for(var e=0,f=d.length;e<f;++e)Qe(this,d[e],a,b);d=d[d.length-1];a>this.t&&(0==c||3==c)&&Z(this.e,d,"left","-"+(a-this.t)+"px");b>this.s&&(1==c||0==c)&&Z(this.e,d,"top","-"+(b-this.s)+"px");Se(this,d,q);this.q=l}};Oe.prototype.Pd=function(){if(this.ja){this.q=l;this.ja=q;var a=Re(this);1<a.length&&Qe(this,a[0],this.Pb,this.Ob);this.jb&&(this.jb(),this.jb=n)}};Oe.prototype.Od=function(){this.q?this.Qb&&this.Qb():this.collapse()};
var Se=function(a,b,c){b=b.parentNode;var d=b.parentNode;"ins"==b.nodeName.toLowerCase()&&!c&&(Je(a.e,b),Je(a.e,d));for(b=d.parentNode;b&&b.style&&"body"!=b.nodeName.toLowerCase();b=b.parentNode)if("visible"!=b.style.overflow&&Z(a.e,b,"overflow","visible"),c){var d=b,e=V(d,"position"),f=V(d,"zIndex");"static"!=e&&"auto"!=f&&Z(a.e,d,"zIndex","auto")}},Pe=function(a){a.m||(a.m=D.getElementById(a.Xc));return a.m};var Te=function(a,b){this.Q=a;this.Td=b;var c;c=a.Ac;var d=D.URL;d instanceof Hc||(d=Tc(d));c instanceof Hc||(c=Tc(c));var e=d,d=c;c=e.fa();var f=!!d.Y;f?Ic(c,d.Y):f=!!d.oa;if(f){var h=c,j=d.oa;Q(h);h.oa=j}else f=!!d.K;f?(h=c,j=d.K,Q(h),h.K=j):f=d.ha!=n;h=d.L;if(f)Jc(c,d.ha);else if(f=!!d.L)if("/"!=h.charAt(0)&&(e.K&&!e.L?h="/"+h:(e=c.L.lastIndexOf("/"),-1!=e&&(h=c.L.substr(0,e+1)+h))),".."==h||"."==h)h="";else if(!(-1==h.indexOf("./")&&-1==h.indexOf("/."))){for(var e=0==h.lastIndexOf("/",0),h=h.split("/"),
j=[],m=0;m<h.length;){var p=h[m++];"."==p?e&&m==h.length&&j.push(""):".."==p?((1<j.length||1==j.length&&""!=j[0])&&j.pop(),e&&m==h.length&&j.push("")):(j.push(p),e=l)}h=j.join("/")}f?(e=c,Q(e),e.L=h):f=""!==d.A.toString();f?Kc(c,d.A.toString()?decodeURIComponent(d.A.toString()):""):f=!!d.na;f&&(f=c,d=d.na,Q(f),f.na=d);d=c.Y+"://"+c.K;c.ha!=n&&(d+=":"+c.ha);this.Lb=c=d;c=this.Q;d={};d.ifrid=c.Rb();d.pu=c.Ac;d.cn=this.Td;d.ppu=Ne(this.Lb);d.lpu=Ne();c=d;this.a=new Td(c);Bc(this.a,z(this.Ba,this));this.Ec();
window.setTimeout(z(this.Xb,this),3E4)};Te.prototype.Ec=function(){if(this.a)try{this.a.G()}catch(a){window.setTimeout(z(this.Ec,this),10)}};Te.prototype.Xb=function(){this.a&&!this.a.v()&&(this.a.j.G=function(){},1==this.a.j.ua&&(this.a.j.Le=function(){}),4==this.a.j.ua&&(this.a.j.Ke=function(){}),this.a.j.ma(),this.a.ma())};
Te.prototype.Ba=function(a){var b=a.split("_");a=b[0];if("expand"==a){if(!this.Q.ib()){for(var c=0,d=a=0,e=0;e<b.length;++e){var f=b[e].charAt(0);"w"==f?c=parseInt(b[e].substring(1),10):"h"==f?a=parseInt(b[e].substring(1),10):"m"==f&&(d=parseInt(b[e].substring(1),10))}var b=this.Q,h=c,j=a,e=Re(b),e=e[e.length-1],e=de(e),f=b.R||E,f=bc(f||window),h=h-b.t,m=j-b.s,j=e.y,m=m>j,p=f.height-(e.y+b.s),j=m||p>=j,m=e.x,h=h>m,b=f.width-(e.x+b.t),b=h||b>=m,e=2;j&&!b?e=3:!j&&b?e=1:!j&&!b&&(e=0);b=e;this.Sb="ok_expand_w"+
c+"_h"+a+"_d"+b;if(0===d)this.Q.expand(c,a,b),this.Bc();else if(1===d&&(d=this.Q,b=z(this.Bc,this),e=z(this.Rd,this),!d.ja&&!d.q&&(d.ja=l,f=Re(d),!(0>=f.length)))){f=f[f.length-1];h=d.R||E;d.jb=b;d.Qb=e;d.Pb=c;d.Ob=a;d.Pa=new Le(f,h,d.Pb,d.Ob,z(d.Pd,d),z(d.Od,d));Se(d,f,l);c=a=d.Pa;c.S=new Ee(q,new Zb(c.R.document));var d=c.S,b=c.R.document.body,r;d.ba&&g(Error("Component already rendered"));d.k||d.wa();b?b.insertBefore(d.k,r||n):d.kb.H.body.appendChild(d.k);(!d.n||d.n.ba)&&d.hb();r=c.S.u;d=r.style;
d.position="absolute";d.left=0;d.top=0;d.background="#666";d.outline="none";he(r,0.7);d.zIndex=999998;M(r,"mousedown",c.zc,q,c);r=c.S.k;r.style.position="fixed";r.style.zIndex=1E6;r.style.outline="none";Je(c.e,c.m);Fe(c.S,l);c=ge(a.m);d=a.S.k;r=parseInt(d.style.left,10)-c.width/2;c=parseInt(d.style.top,10)-c.height/2;d=de(a.m);Z(a.e,a.m,"left",0);Z(a.e,a.m,"top",0);Z(a.e,a.m,"position","fixed");Z(a.e,a.m,"outline","none");a.xa=new ve(a.m,[d.x,d.y],[r,c],a.Nd,we);M(a.xa,"end",a.Qd,q,a);a.xa.play()}}}else"collapse"==
a&&this.Q.ib()&&(this.Q.collapse(),Ue(this,"ok_collapse_w"+this.Q.Nb()+"_h"+this.Q.Mb()))};var Ue=function(a,b){a.a.send("expandable_ad",b)};Te.prototype.Bc=function(){this.Sb&&(Ue(this,this.Sb),this.Sb=n)};Te.prototype.Rd=function(){Ue(this,"initiateCollapse")};
var We=function(a){var b=a.google_frame_id;b||(b="google_frame_"+Math.floor(2147483647*Math.random()));var c=a.google_ad_url,d=parseInt(a.google_ad_width,10),e=parseInt(a.google_ad_height,10),f=a.google_container_id,c=Ve(b,c,d,e,f);return a[b]=c};B("ExpandableAdSlotFactory.createIframeFromWindow",We);
var Ve=function(a,b,c,d,e,f,h){if(!a||!b||0>=c||0>=d)return n;var j=gd(),m=ya(D.URL);b=Xe(b,j,m);var m=a,p="<iframe allowtransparency=true frameborder=0 height="+d+" hspace=0 id="+m+" marginheight=0 marginwidth=0 name="+m+' scrolling=no src="'+b+'" style="left:0;position:absolute;top:0" vspace=0 width='+c+"></iframe>";if(h)m=p;else var r="border:none;height:"+d+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+c+"px",m=['<ins style="display:inline-table;',r,'">','<ins id="',m+"_anchor",
'" style="display:block;',r,'">',p,"</ins></ins>"],m=m.join("");(e=e?D.getElementById(e):n)?e.innerHTML=m:D.write(m);a=new Oe(a,b,c,d,f,h);return new Te(a,j)};B("ExpandableAdSlotFactory.createIframe",Ve);function Xe(a,b,c){return a+(-1==a.indexOf("?")?"?":"&")+(c?"google_debug&":"")+"xpc="+b+"&p="+encodeURIComponent(D.location.protocol)+"//"+encodeURIComponent(D.location.host)}
var Ye=function(a,b,c,d){if(!a||!b||0>=c||0>=d)return n;var e=gd(),f=ya(D.URL);b=Xe(b,e,f);var f=a,h=b,j=c,m=d,p=document.createElement("iframe");p.style.cssText="border:none;height:"+m+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+j+"px";p.name=f;p.id=f;p.src=h;p.style.cssText="left:0;position:absolute;top:0";p.width=j;p.height=m;p.frameBorder=0;p.hspace=0;p.vspace=0;p.scrolling="no";p.Ne=0;p.Oe=0;p.Me=l;f=p;b=new Oe(a,b,c,d);window["expandableAdSlot_"+a]=new Te(b,e);a=f;c=
"border:none;height:"+d+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+c+"px";d=D.createElement("ins");d.style.cssText="display:inline-table;"+c;e=D.createElement("ins");e.style.cssText="display:block;"+c;e.appendChild(a);d.appendChild(e);return c=d};B("DhtmlExpandableIframeFactory.createElement",Ye);var $=function(){this.q=this.N=q;this.ac=l;this.t=this.s=this.ca=this.ka=0;this.ub=q;this.qa=this.Qc=this.Mc=this.Va=n;this.Jc=3E3;this.Rc=2E3;this.Xd=100;this.vb=this.Nc=0;this.Sc={};this.pb=0;this.Ic=l;this.bc="google_expansion_overlay";this.cc="google_progress_bar"},Ze={CLICK_TO_EXPAND:29,HOVER_TO_EXPAND:30,GENERIC_ENGAGEMENT:32,VIDEO_PLAY:33,VIDEO_UNMUTE:34,VIDEO_VIEW_TIMER:35,MOUSE_HOVER:36,SWIPE:37,VIDEO_REPLAY:10001,VIDEO_PAUSE:10002,VIDEO_STOP:10003,VIDEO_MUTE:10004,VIDEO_MIDPOINT:10005,VIDEO_COMPLETE:10006,
VIDEO_INTERACTION:10007,FULL_SCREEN:10008,MANUAL_CLOSE:10009,CONTRACTION:10010};$.prototype.Fe={29:"expansion",30:"expansion_hover",32:"generic_engagement",33:"rm_video_play",34:"rm_video_unmute",35:"rm_video_view_timer",36:"mouse_hover",37:"swipe",10001:"rm_video_replay",10002:"rm_video_pause",10003:"rm_video_stop",10004:"rm_video_mute",10005:"rm_video_midpoint",10006:"rm_video_complete",10007:"rm_video_interaction",10008:"rm_fullscreen",10009:"rm_manual_close",10010:"contraction"};
var $e=function(a,b){a.N=l;if(!b)return a.N=q,a.N;var c=a,d,e=b.width,f=b.height,h=b.expansionCallback,j=b.collapseCallback;d=b.initiateCollapseCallback;var m=b.expansionMode,p=b.chargeForExpansion,e=fa(e)&&0<e&&fa(f)&&0<f,h=y(h)&&y(j)&&(y(d)||"undefined"===typeof d),h=e&&h;if("undefined"!==typeof m){if(!fa(m)||0>m||2<=m)h=q;1===m&&!d&&(h=q)}"undefined"!==typeof p&&"boolean"!=typeof p&&(h=q);d=h;c.N=d;a.N&&(a.ca=b.width,a.ka=b.height,a.Yc=b.expansionCallback,a.qb=b.collapseCallback,a.sd=b.initiateCollapseCallback,
a.pb=b.expansionMode||0,a.Ic="undefined"===typeof b.chargeForExpansion||b.chargeForExpansion,1===a.pb&&a.fd(q),c=D.body,wa(c,"mousedown",z(a.pe,a)),H||I&&fb?(wa(c,"mouseenter",z(a.ud,a)),wa(c,"mouseleave",z(a.td,a))):(wa(c,"mouseover",z(a.ud,a)),wa(c,"mouseout",z(a.td,a))));return a.N};s=$.prototype;s.Mb=function(){return this.s};s.Nb=function(){return this.t};s.se=function(){return this.ka};s.te=function(){return this.ca};s.ib=function(){return this.q};s.ue=function(){return this.N};
s.fd=function(a){this.ac=a};
var af=function(a){return!a.N||a.q||a.ja()?q:l},cf=function(a,b,c,d){a.q=l;a.Mc=new Date;if(a.ac){var e=a,f=b,h=c,j=d;if(1===e.pb)f=Math.round((f-e.t)/2),0<f&&(D.body.style.marginLeft=f+"px"),f=Math.round((h-e.s)/2),0<f&&(D.body.style.marginTop=f+"px");else{if(0==j||3==j)f-=e.t,0<f&&(D.body.style.marginLeft=f+"px");if(0==j||1==j)f=h-e.s,0<f&&(D.body.style.marginTop=f+"px")}}if(f=D.getElementById("abgc"))f.style.visibility="hidden";bf(a);f=a.qa&&new Date-a.qa<a.Jc?29:30;h=k;a.Ic||(h={no_charge:l});
a.ec(f,h);"function"==typeof a.Yc&&a.Yc(b,c,d)},df=function(a,b,c){a.q=q;a.Qc=new Date;a.ac&&(D.body.style.marginLeft="0",D.body.style.marginTop="0");var d=D.getElementById("abgc");d&&(d.style.visibility="visible");bf(a);a.qa=n;d={};d.explen=a.Qc-a.Mc;d.no_charge=l;a.ec(10010,d);"function"==typeof a.qb&&a.qb(b,c)};$.prototype.pe=function(){this.q||(this.qa=new Date)};
$.prototype.td=function(){var a=this.ja();clearTimeout(this.Nc);bf(this);this.ub=q;this.qa=n;if(a){var b=E.location.protocol,a="https:"==b?"pagead2.googleadservices.com":"pagead2.googlesyndication.com",c=this.Va?new Date-this.Va:0,a=[b,"//",a,"/pagead/gen_204?id=mouseout&hovlen=",c,"&ai=",E.EXPANSION_CLICK_INFO].join("");xa(a)}this.Va=n};$.prototype.ud=function(){this.ub=l;this.Va||(this.Va=new Date)};
var bf=function(a){clearInterval(a.od);clearInterval(a.vb);a.vb=0;var b=D.getElementById(a.bc);a=D.getElementById(a.cc);b&&a&&(b.style.display="none",b.style.bottom="-20px",a.style.width="0%")};$.prototype.ja=function(){return 0!=this.vb};
$.prototype.ec=function(a,b){if("number"===typeof a){var c=b||{},d;if(E.ENABLE_CPE&&!this.Ee&&1E4>a&&!c.hasOwnProperty("no_charge")){if(!E.ENGAGEMENT_URL)return;this.Ee=l;c=a;/ctype=\d+/.test(E.ENGAGEMENT_URL)?d=E.ENGAGEMENT_URL.replace(/ctype=\d+/,"ctype="+c):(d=E.ENGAGEMENT_URL.indexOf("?")+1,d=[E.ENGAGEMENT_URL.substr(0,d),"ctype=",c,"&",E.ENGAGEMENT_URL.substr(d)].join(""))}else{if(!E.CREATIVE_CONVERSION_URL)return;d=this.Sc[a];d=[E.CREATIVE_CONVERSION_URL,"&label=",this.Fe[a],d?"&noconv=1":"",
"&random=",(new Date).getTime()].join("");c.hasOwnProperty("explen")&&"number"===typeof c.explen&&(d=[d,"&explen=",c.explen].join(""))}this.Sc[a]=l;xa(d)}};
var ef=function(a){B("CreativeToolset",a);B("CreativeToolset.prototype.collapseWindow",a.prototype.xd);B("CreativeToolset.prototype.enableExpansion",a.prototype.yd);B("CreativeToolset.prototype.expandWindow",a.prototype.zd);B("CreativeToolset.prototype.getCollapsedHeight",a.prototype.Mb);B("CreativeToolset.prototype.getCollapsedWidth",a.prototype.Nb);B("CreativeToolset.prototype.getExpandedHeight",a.prototype.se);B("CreativeToolset.prototype.getExpandedWidth",a.prototype.te);B("CreativeToolset.prototype.isExpanded",
a.prototype.ib);B("CreativeToolset.prototype.isExpansionEnabled",a.prototype.ue);B("CreativeToolset.prototype.shouldMaintainCoordinates",a.prototype.fd);B("CreativeToolset.prototype.reportEngagement",a.prototype.ec);B("EngagementAction",Ze);B("CreativeToolset.ExpansionMode",Me)};var ff=function(){$.call(this)};C(ff,$);s=ff.prototype;s.yd=function(a){return $e(this,a)&&this.yc()?l:q};s.yc=function(){var a=bc(E||window);this.t=a.width;this.s=a.height;return"function"==typeof iframer.expand&&"function"==typeof iframer.collapse?(this.re=iframer.expand,this.qe=iframer.collapse,l):q};s.zd=function(a,b){if(af(this)){var c=this.ca,d=this.ka;a&&b&&(c=a,d=b);this.re({width:c,height:d},z(this.ze,this))}};s.xd=function(){this.N&&this.q&&this.qe({},z(this.ve,this))};
s.ze=function(a){cf(this,a.width,a.height,a.direction)};s.ve=function(){df(this,this.t,this.s)};s.Ba=function(a){a=a.split("_");if("ok"==a[0]){for(var b,c,d,e=2;e<a.length;++e){var f=a[e].charAt(0),h=parseInt(a[e].substring(1),10);"w"==f?b=h:"h"==f?c=h:"d"==f&&(d=h)}"expand"==a[1]&&"number"==typeof b&&"number"==typeof c&&"number"==typeof d&&0<b&&0<c&&0<=d?cf(this,b,c,d):"collapse"==a[1]&&("number"==typeof b&&"number"==typeof c&&0<b&&0<c)&&df(this,b,c)}};window.USE_IFRAMES_API===l&&ef(ff);var gf=function(){$.call(this)};C(gf,$);s=gf.prototype;s.yd=function(a){return $e(this,a)?(this.yc(D.URL),l):q};s.yc=function(a){var b=bc(E||window);this.t=b.width;this.s=b.height;b=new Hc(a);a=b.A.get("xpc");var b=b.A.get("p"),c={};c.cn=a;c.ph=b;c.ppu=Ne(b);c.lpu=Ne();a=c;this.a=new Td(a);Bc(this.a,z(this.Ba,this));this.a.G(function(){});window.setTimeout(z(this.Xb,this),3E4)};s.Xb=function(){this.a&&!this.a.v()&&(this.a=n)};
s.zd=function(a,b){if(af(this)){var c=this.ca,d=this.ka;a&&b&&(c=a,d=b);var e=["expand_w",c,"_h",d,"_m",this.pb].join(""),f=c=z(function(){hf(this,e)},this);if("function"==typeof f&&af(this))if(c=z(function(){this.ub&&this.ub&&f()},this),this.qa&&new Date-this.qa<this.Jc)c();else{this.Nc=setTimeout(c,this.Rc);var h=D.getElementById(this.bc),j=D.getElementById(this.cc);if(!h){var m=E.EXPANSION_TEXT||"Expanding...",c=E.EXPANSION_RIGHT_TO_LEFT&&"string"!==typeof E.EXPANSION_RIGHT_TO_LEFT||q,d=9999999,
h=D.createElement("div");h.id=this.bc;var p=D.createElement("span");p.innerHTML=m;p.style.fontSize="14px";16<=m.length&&(p.style.fontSize="12px");p.style.fontFamily="Arial,sans-serif";p.style.letterSpacing="0.05em";p.style.position="absolute";p.style.bottom="1px";p.style.zIndex=d;j=D.createElement("div");j.id=this.cc;j.style.zIndex=d;j.style.background="#eee";j.style.width="0%";j.style.height="20px";c?(p.style.right="5px",j.style.cssFloat="right",p.setAttribute("dir","rtl")):p.style.left="5px";h.appendChild(p);
h.appendChild(j);D.body.appendChild(h);m=h.style;m.position="absolute";c?(m.right=0,Yd(h,"border-top-left-radius","5px"),Yd(h,"-moz-border-top-left-radius","5px"),Yd(h,"-webkit-border-top-left-radius","5px"),m.textAlign="right"):(m.left=0,Yd(h,"border-top-right-radius","5px"),Yd(h,"-moz-border-top-right-radius","5px"),Yd(h,"-webkit-border-top-right-radius","5px"),m.textAlign="left");m.bottom="-20px";m.padding=0;m.height="20px";m.width="120px";m.lineHeight="20px";m.overflow="hidden";m.zIndex=d;he(h,
0.75);m.background="#aaa";Yd(h,"pointer-events","none")}bf(this);h.style.display="";var r=20,x=0,c=z(function(){0>=r?clearInterval(this.od):(r-=1,h.style.bottom="-"+r+"px")},this),d=z(function(){100<=x?bf(this):(x+=1,j.style.width=x+"%")},this);this.od=setInterval(c,this.Xd/r);this.vb=setInterval(d,this.Rc/100)}}};s.xd=function(){this.N&&this.q&&hf(this,"collapse")};var hf=function(a,b){a.a&&a.a.v()&&a.a.send("expandable_ad",b)};
gf.prototype.Ba=function(a){a=a.split("_");if("ok"===a[0]){for(var b,c,d,e=2;e<a.length;++e){var f=a[e].charAt(0),h=parseInt(a[e].substring(1),10);"w"==f?b=h:"h"==f?c=h:"d"==f&&(d=h)}"expand"==a[1]&&"number"==typeof b&&"number"==typeof c&&"number"==typeof d&&0<b&&0<c&&0<=d?cf(this,b,c,d):"collapse"==a[1]&&("number"==typeof b&&"number"==typeof c&&0<b&&0<c)&&df(this,b,c)}else"initiateCollapse"===a[0]&&"function"===typeof this.sd&&this.sd()};window.USE_IFRAMES_API!==l&&ef(gf);ya(document.URL)&&document.write('<script src="https://web.archive.org/web/20121212183555/http://pagead2.googlesyndication.com/pagead/expansion_embed_dbg.js"><\/script>');})()


}
/*
     FILE ARCHIVED ON 18:35:55 Dec 12, 2012 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 04:28:38 Mar 09, 2025.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 0.639
  exclusion.robots: 0.019
  exclusion.robots.policy: 0.008
  esindex: 0.011
  cdx.remote: 71.839
  LoadShardBlock: 346.93 (6)
  PetaboxLoader3.datanode: 300.747 (7)
  PetaboxLoader3.resolve: 84.08 (2)
  load_resource: 88.409
*/